from search_methods.binary import BinarySearch
from search_methods.block import BlockSearch
from search_methods.dichotomy import Dihotomy
from search_methods.fibonacci import Fibonachy
from search_methods.golden_ratio import GoldenFraction
from search_methods.passive_block import PassiveBlockSearch
from search_methods.tangent import TangentMethod
from search_methods.parabola import ParabolMethod
